# Generated by Django 4.2.7 on 2023-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Afganistan'), (2, 'Albania')], verbose_name='title'),
        ),
    ]
